# Generated by Django 4.2.7 on 2026-02-06 10:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('super_admin', 'SUPER_ADMIN'), ('manager', 'MANAGER'), ('support', 'SUPPORT'), ('kyc_associate', 'KYC_ASSOCIATE'), ('ca_finance', 'CA_FINANCE'), ('developer', 'DEVELOPER')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
